; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
src_filter = +<*> -<.git/> -<.svn/> -<example/> -<examples/> -<test/> -<tests/>s
lib_deps = tmrh20/RF24@^1.3.11
monitor_port = ${env:receiver.upload_port}
monitor_speed = 115200

[env:transmitter]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_port = /dev/ttyUSB0
src_filter = ${env.src_filter} -<mainReceiver.cpp>
lib_deps = tmrh20/RF24@^1.3.11

[env:receiver]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_port = /dev/ttyUSB1
src_filter = ${env.src_filter} -<mainTransmitter.cpp>
lib_deps = tmrh20/RF24@^1.3.11
